services:
  # Backend FastAPI service (production)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fusevault-backend-prod
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    networks:
      - fusevault-network
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  # Web3 Storage Service (production)
  web3-storage:
    build:
      context: ./web3-storage-service
      dockerfile: Dockerfile
    container_name: fusevault-web3-storage-prod
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - ./web3-storage-service/.env
    volumes:
      - web3_storage_uploads:/app/upload_queue
    networks:
      - fusevault-network
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  # Frontend React service (production)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL:-http://localhost:8000}
    container_name: fusevault-frontend-prod
    restart: unless-stopped
    ports:
      - "3001:80"
    depends_on:
      - backend
      - web3-storage
    networks:
      - fusevault-network
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

volumes:
  web3_storage_uploads:
    driver: local

networks:
  fusevault-network:
    driver: bridge